import Notebook1 from "../../images/notebook1.png";
import Notebook2 from "../../images/notebook2.png";
import Notebook3 from "../../images/notebook3.png";

export const data = [
    {
        title: "Standard notebook",
        text: "Notebook will be an indispensable assistant for your important affairs and ideas",
        image: Notebook1,
        id: 0,
        price: 99.99,
        producer: "China",
        targetAge: 25,
        barCode: "00000",
    },
    {
        title: "Thick cover",
        text: "Everyone needs extra protection!",
        image: Notebook2,
        id: 1,
        price: 199.99,
        producer: "Japan",
        targetAge: 15,
        barCode: "1234",
    },
    {
        title: "Wide lines",
        text: "Notebooks for any task",
        image: Notebook3,
        id: 2,
        price: 149.99,
        producer: "China",
        targetAge: 10,
        barCode: "4321",
    },
    {
        title: "Dear cover",
        text: "Golden paper it's very dear!",
        image: Notebook2,
        id: 3,
        price: 9999,
        producer: "USA",
        targetAge: 18,
        barCode: "987654321",
    },
    {
        title: "Discount!!!",
        text: "ONLY 100 UAH!",
        image: Notebook3,
        id: 4,
        price: 100,
        producer: "Japan",
        targetAge: 12,
        barCode: "00000",
    },
    {
        title: "Cheap notebook",
        text: "Very cheap",
        image: Notebook1,
        id: 5,
        price: 9.99,
        producer: "Ukraine",
        targetAge: 8,
        barCode: "8888",
    },
    {
        title: "Rare notebook",
        text: "With Atlantida!",
        image: Notebook3,
        id: 6,
        price: 3779,
        producer: "Japan",
        targetAge: 99,
        barCode: "7777",
    },
    {
        title: "Apple notebook",
        text: "You need this!",
        image: Notebook2,
        id: 7,
        price: 5000,
        producer: "USA",
        targetAge: 35,
        barCode: "000",
    },
    {
        title: "Giant notebook",
        text: "For big people",
        image: Notebook1,
        id: 8,
        price: 499,
        producer: "Poland",
        targetAge: 50,
        barCode: "9999",
    },
];